image: sbtscala/scala-sbt

stages:
  - compile
  - test

compile_job:
  stage: compile
  script: 
    - echo "compiling..."
    - make clean
    - sbt clean compile
    - echo "compile successful!"

test_job: 
  stage: test
  script:
    - echo "testing..."
    - sbt test
    - echo "test successful!"