image: hzli1202/wacc_test_env

stages:
  - compile
  - unit_tests
  - integration_tests

cache:
  key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
  untracked: true
  paths:
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

compile_job:
  stage: compile
  script: 
    - echo "compiling..."
    - sbt clean compile
    - echo "compile successful!"

syntax_test: 
  stage: unit_tests
  script:
    - echo "Running front-end syntax unit tests..."
    - sbt "Test / testOnly *SyntaxChecker*"
    - echo "TEST SUCCESSFUL!"

semantic_test: 
  stage: unit_tests
  script:
    - echo "Running front-end semantic unit tests..."
    - sbt "Test / testOnly *SemanticChecker*"
    - echo "TEST SUCCESSFUL!"


backend_unit_test:
  stage: unit_tests
  script:
    - echo "Running back-end unit tests..."
    - sbt "Test / testOnly *CodeGen*"
    - echo "TEST SUCCESSFUL!"

integration_test:
  stage: integration_tests
  script:
    - echo "Running integration tests..."
    - sbt "Test / testOnly *IntegrationTests*"
    - echo "TEST SUCCESSFUL!"

    